// Generated by CoffeeScript 1.6.3
(function() {
  var $, mainNav, stickyMenu,
    _this = this;

  $ = jQuery;

  $(document).ready(function() {
    var changeTab, intervalFunc, x;
    if ($(".tabs").length) {
      x = 1;
      changeTab = function() {
        return $(".tabs").find('span').eq(x).click();
      };
      intervalFunc = setInterval(changeTab, 6000);
      $(".tabs").find('span').on("click", function(event) {
        var idx;
        event.preventDefault();
        event.stopPropagation();
        if ($(this).hasClass('active')) {
          return false;
        } else {
          idx = $(this).index();
          $(this).parents(".tabs-section").find(".tabs span").removeClass("active");
          $(this).addClass('active').focus();
          $(this).parents(".tabs-section").find(".tab-body").removeClass('opened').eq(idx).addClass('opened');
        }
        idx = $(this).index() + 1;
        if (idx === $(".tabs").find('span').length) {
          x = 0;
        } else {
          x = idx;
        }
        clearInterval(intervalFunc);
        return intervalFunc = setInterval(changeTab, 6000);
      });
    }
  });

  jQuery(window).load(function() {
    $(".tabs").find('span').eq(0).click();
    mainNav();
    stickyMenu();
    $("body").on("click", function(event) {
      if ($(event.target).hasClass("link")) {
        return false;
      } else {
        if ($(".mobile").find("section").hasClass("opened")) {
          return $(".mobile").find("section").removeClass("opened").find("nav").slideUp();
        }
      }
    });
  });

  $(window).scroll(function() {
    stickyMenu();
  });

  $(window).resize(function() {
    if ($(window).width() > 992) {
      return $(".mobile").show();
    }
  });

  stickyMenu = function() {
    var positionFooter, positionWrapper, scrollTopPosition, winHeight;
    if ($(window).width() > 800) {
      positionWrapper = $('.wrapper ').offset().top;
      positionFooter = $(".footer").offset().top;
      scrollTopPosition = 0;
      winHeight = $(window).height();
      if (navigator.appCodeName === "Netscape") {
        scrollTopPosition = $('body').scrollTop();
      } else {
        scrollTopPosition = $('html').scrollTop();
      }
      if (scrollTopPosition + winHeight - positionFooter > 0) {
        return $(".left-column").removeClass("fixed");
      } else if (positionWrapper - scrollTopPosition <= 0) {
        return $(".left-column").addClass("fixed");
      } else {
        return $(".left-column").removeClass("fixed");
      }
    }
  };

  mainNav = function() {
    $(".main-nav .mobile > section").find("a").on("click", function(ev) {
      ev.preventDefault();
      if ($(this).parents("section").hasClass("opened")) {
        return $(this).parents("section").removeClass("opened").find("nav").slideUp();
      } else if ($(".main-nav > section").hasClass("opened")) {
        $(".main-nav > section.opened").removeClass("opened").find("nav").slideUp();
        return $(this).parents("section").addClass("opened").find("nav").slideDown();
      } else {
        return $(this).parents("section").addClass("opened").find("nav").slideDown();
      }
    });
    return $(".header-mobile").on("click", function() {
      $(".mobile").slideToggle(function() {
        return $(".mobile").find("section").removeClass("opened").find("nav").slideUp();
      });
    });
  };

}).call(this);
